name: Cypress Test on Firefox
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    
    name: E2E Test on Firefox
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v5
        with:
          browser: firefox
