name: Cypress Test in custom container
on: [push]
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    name: Cypress Tests on docker container
    # Cypress Docker image with Chrome v107 pre-installed
    container: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
    
